name: Update Test-Submodule
on:
  # Run weekly - Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Watch for changes in the test-submodule repo
  repository_dispatch:
    types: [update-submodule]

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'  # Needed to check out submodules
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      # Check if submodule exists, if not add it
      - name: Check and add submodule if needed
        run: |
          if [ ! -f ".gitmodules" ] || ! grep -q "submodule-folder" .gitmodules; then
            echo "Adding test-submodule as a new submodule"
            git submodule add https://github.com/atharva-2001/test-submodule submodule-folder
          else
            echo "test-submodule submodule already exists"
          fi
      
      # Update the submodule
      - name: Update test-submodule
        run: |
          echo "Updating test-submodule"
          git submodule update --remote --merge submodule-folder
      
      # Commit and push changes
      - name: Commit and push changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update test-submodule to latest version"
            git push
          fi
